# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evl_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# 测试PyQt5运行 CJW
import PyQt5
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(825, 579)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txt_path = QtWidgets.QLineEdit(Form)
        self.txt_path.setObjectName("txt_path")
        self.horizontalLayout.addWidget(self.txt_path)
        self.btn_find_xls = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_find_xls.sizePolicy().hasHeightForWidth())
        self.btn_find_xls.setSizePolicy(sizePolicy)
        self.btn_find_xls.setMinimumSize(QtCore.QSize(40, 1))
        self.btn_find_xls.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_find_xls.setObjectName("btn_find_xls")
        self.horizontalLayout.addWidget(self.btn_find_xls)
        self.btn_open_xls = QtWidgets.QPushButton(Form)
        self.btn_open_xls.setObjectName("btn_open_xls")
        self.horizontalLayout.addWidget(self.btn_open_xls)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.list_xls = QtWidgets.QTableView(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.list_xls.sizePolicy().hasHeightForWidth())
        self.list_xls.setSizePolicy(sizePolicy)
        self.list_xls.setAutoFillBackground(False)
        self.list_xls.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_xls.setTabKeyNavigation(True)
        self.list_xls.setAlternatingRowColors(True)
        self.list_xls.setObjectName("list_xls")
        self.verticalLayout.addWidget(self.list_xls)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cob_eval = QtWidgets.QComboBox(Form)
        self.cob_eval.setObjectName("cob_eval")
        self.horizontalLayout_2.addWidget(self.cob_eval)
        self.btn_eval = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_eval.sizePolicy().hasHeightForWidth())
        self.btn_eval.setSizePolicy(sizePolicy)
        self.btn_eval.setObjectName("btn_eval")
        self.horizontalLayout_2.addWidget(self.btn_eval)
        self.btn_save = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_debug = QtWidgets.QPushButton(Form)
        self.btn_debug.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_debug.sizePolicy().hasHeightForWidth())
        self.btn_debug.setSizePolicy(sizePolicy)
        self.btn_debug.setObjectName("btn_debug")
        self.horizontalLayout_2.addWidget(self.btn_debug)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.txt_debug_info = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txt_debug_info.sizePolicy().hasHeightForWidth())
        self.txt_debug_info.setSizePolicy(sizePolicy)
        self.txt_debug_info.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txt_debug_info.setObjectName("txt_debug_info")
        self.verticalLayout.addWidget(self.txt_debug_info)
        self.verticalLayout.setStretch(3, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "水质评价"))
        self.label.setText(_translate("Form", "表格路径："))
        self.btn_find_xls.setText(_translate("Form", "..."))
        self.btn_open_xls.setText(_translate("Form", "打开表格"))
        self.label_2.setText(_translate("Form", "评价方法："))
        self.btn_eval.setText(_translate("Form", "评价"))
        self.btn_save.setText(_translate("Form", "保存"))
        self.btn_debug.setText(_translate("Form", "测试"))
        self.txt_debug_info.setPlainText(_translate("Form", "0905"))



#       这样就能继承这个窗口
#       这两个个是窗口必须要继承的
class MyGui(QMainWindow,Ui_Form):
    #       初始化窗口
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)


if __name__ == '__main__':
    import sys
    app = PyQt5.QtWidgets.QApplication(sys.argv)
    MyUiStart = MyGui()
    MyUiStart.show()#       ui就会显示出来
    sys.exit(app.exec_())
